# PjPluginManifest.cmake
#
# CMake helper that emits a plugin manifest sidecar JSON alongside a plugin
# shared library at build time. The sidecar lets a host scan all installed
# plugins at startup without dlopen'ing any — essential when the plugin
# count grows past a dozen or so.
#
# The sidecar is deliberately additive: the DSO still exports its manifest
# at runtime via get_plugin_manifest() (family-dependent). The host verifies
# at activation that the sidecar and the DSO agree; on mismatch, the DSO
# wins and a warning is logged.
#
# Design: reuse the plugin's existing manifest.json file (the same file
# pj_embed_manifest uses to bake the manifest into the DSO) and augment it
# with two autogenerated keys:
#   - "abi_major": matches PJ_ABI_VERSION in the C header at build time.
#   - "family":    one of data_source, message_parser, toolbox, dialog.
# Everything else (name, version, description, file_extensions, encoding,
# category, etc.) passes through verbatim from the source manifest.json.
#
# Usage:
#   include(PjPluginManifest)   # auto-included by the root CMakeLists.txt
#   add_library(csv_source_plugin SHARED csv_source.cpp)
#   pj_emit_plugin_manifest(csv_source_plugin
#     FAMILY        data_source
#     MANIFEST_FILE ${CMAKE_CURRENT_SOURCE_DIR}/manifest.json
#   )
#
# Writes <build-dir>/csv_source_plugin.pjmanifest.json next to the .so,
# and installs it to ${CMAKE_INSTALL_LIBDIR} alongside the DSO.

function(pj_emit_plugin_manifest TARGET)
  set(_options)
  set(_oneValueArgs FAMILY MANIFEST_FILE ABI_MAJOR)
  set(_multiValueArgs)
  cmake_parse_arguments(ARG "${_options}" "${_oneValueArgs}" "${_multiValueArgs}" ${ARGN})

  if(NOT ARG_FAMILY)
    message(FATAL_ERROR "pj_emit_plugin_manifest(${TARGET}): FAMILY is required")
  endif()

  set(_valid_families data_source message_parser toolbox dialog)
  list(FIND _valid_families "${ARG_FAMILY}" _family_idx)
  if(_family_idx LESS 0)
    message(FATAL_ERROR
      "pj_emit_plugin_manifest(${TARGET}): FAMILY \"${ARG_FAMILY}\" is invalid. "
      "Must be one of: ${_valid_families}")
  endif()

  if(NOT ARG_MANIFEST_FILE)
    set(ARG_MANIFEST_FILE "${CMAKE_CURRENT_SOURCE_DIR}/manifest.json")
  endif()
  if(NOT EXISTS "${ARG_MANIFEST_FILE}")
    message(FATAL_ERROR
      "pj_emit_plugin_manifest(${TARGET}): MANIFEST_FILE not found: ${ARG_MANIFEST_FILE}")
  endif()

  if(NOT ARG_ABI_MAJOR)
    # Matches PJ_ABI_VERSION in pj_base/plugin_data_api.h. Bump in lockstep.
    set(ARG_ABI_MAJOR 4)
  endif()

  # Track manifest edits so CMake reconfigures when the source changes.
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${ARG_MANIFEST_FILE}")

  # Read + validate required keys.
  file(READ "${ARG_MANIFEST_FILE}" _src_json)
  string(JSON _name     ERROR_VARIABLE _err GET "${_src_json}" "name")
  if(_err)
    message(FATAL_ERROR "${ARG_MANIFEST_FILE}: missing required \"name\" key")
  endif()
  string(JSON _version  ERROR_VARIABLE _err GET "${_src_json}" "version")
  if(_err)
    message(FATAL_ERROR "${ARG_MANIFEST_FILE}: missing required \"version\" key")
  endif()

  # Augment: add abi_major + family. string(JSON SET) preserves other keys.
  set(_sidecar_json "${_src_json}")
  string(JSON _sidecar_json SET "${_sidecar_json}" "abi_major" "${ARG_ABI_MAJOR}")
  string(JSON _sidecar_json SET "${_sidecar_json}" "family"    "\"${ARG_FAMILY}\"")

  # Write to build tree. The file lives next to the DSO.
  set(_sidecar_path "${CMAKE_CURRENT_BINARY_DIR}/${TARGET}.pjmanifest.json")
  file(WRITE "${_sidecar_path}" "${_sidecar_json}\n")

  # Copy sidecar next to the built DSO so a host scanning the build tree
  # finds it beside the .so. Handles out-of-source per-config output dirs.
  add_custom_command(
    TARGET ${TARGET} POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E copy_if_different
      "${_sidecar_path}"
      "$<TARGET_FILE_DIR:${TARGET}>/${TARGET}.pjmanifest.json"
    COMMENT "Copying ${TARGET}.pjmanifest.json next to DSO"
    VERBATIM
  )

  # Install sidecar to the same directory as the DSO (MODULE or SHARED).
  get_target_property(_type ${TARGET} TYPE)
  if(_type STREQUAL "MODULE_LIBRARY" OR _type STREQUAL "SHARED_LIBRARY")
    install(FILES "${_sidecar_path}"
      DESTINATION "${CMAKE_INSTALL_LIBDIR}"
    )
  endif()
endfunction()
