# PjPlugin.cmake — CMake helpers for authoring PlotJuggler plugin shared libraries.
#
# Shipped with the plotjuggler_sdk::plugin_sdk component: find_package(plotjuggler_sdk
# COMPONENTS plugin_sdk) and the in-tree add_subdirectory() build both include it, so plugin
# CMakeLists never copy these helpers.
#
#   pj_configure_plugin(<target> FAMILIES <family>... [options])
#     Turn a SHARED/MODULE target into a correct PlotJuggler plugin: symbol isolation + rpath,
#     manifest validation + sidecar, optional manifest header embed, export allowlist + gate.
#   pj_embed_file(<target> FILE <path> HEADER <path> VAR_NAME <identifier>)
#     Embed any file (Qt Designer .ui XML, manifest.json, ...) as a constexpr char array.
#   pj_harden_plugin_exports(<target> [FAMILIES ...] [REQUIRED_EXPORTS ...] [EXTRA_EXPORTS ...])
#     Restrict a plugin DSO's dynamic exports to the ABI entry points (Linux/ELF only).
#   pj_emit_plugin_manifest(<target> FAMILY <family> [MANIFEST_FILE <path>] [ABI_MAJOR <n>])
#     Deprecated (0.25.0) alias of pj_configure_plugin(... NO_EXPORT_HARDENING).

include_guard(GLOBAL)
include(GNUInstallDirs)  # CMAKE_INSTALL_LIBDIR — the sidecar install rule needs it

function(_pj_plugin_check_family CONTEXT FAMILY)
  set(_families data_source message_parser toolbox dialog)
  if(NOT FAMILY IN_LIST _families)
    message(FATAL_ERROR "${CONTEXT}: family \"${FAMILY}\" is invalid. Must be one of: ${_families}")
  endif()
endfunction()

function(_pj_plugin_check_target CONTEXT TARGET)
  if(NOT TARGET "${TARGET}")
    message(FATAL_ERROR "${CONTEXT}: \"${TARGET}\" is not a target — call add_library() first")
  endif()
endfunction()

# ---------------------------------------------------------------------------
# pj_embed_file
# ---------------------------------------------------------------------------
# pj_embed_file(<target>
#   FILE     <path>          # input, relative to CMAKE_CURRENT_SOURCE_DIR
#   HEADER   <path>          # generated header, relative to CMAKE_CURRENT_BINARY_DIR
#   VAR_NAME <identifier>)   # name of the generated `inline constexpr char <VAR_NAME>[]`
#
# Generates, at configure time, a header holding the file's bytes plus a NUL terminator:
#   inline constexpr char kMyDialogUi[] = { '\x3c', '\x3f', ..., '\x00' };
# and adds the header's directory to the target's PRIVATE include path, so the plugin does
#   #include "my_dialog_ui.hpp"
#   std::string ui_content() const override { return kMyDialogUi; }
#
# Bytes rather than a string literal: MSVC caps one literal at 16380 characters (C2026) and
# a raw string would need a delimiter that cannot appear in the file. The input is tracked as
# a configure dependency (editing it re-runs CMake); the header is rewritten only when its
# content changes, so a reconfigure does not recompile every translation unit including it.
function(pj_embed_file TARGET)
  set(_options)
  set(_oneValueArgs FILE HEADER VAR_NAME)
  set(_multiValueArgs)
  cmake_parse_arguments(ARG "${_options}" "${_oneValueArgs}" "${_multiValueArgs}" ${ARGN})
  set(_ctx "pj_embed_file(${TARGET})")
  if(ARG_UNPARSED_ARGUMENTS)
    message(FATAL_ERROR "${_ctx}: unknown arguments: ${ARG_UNPARSED_ARGUMENTS}")
  endif()
  _pj_plugin_check_target("${_ctx}" "${TARGET}")
  foreach(_required FILE HEADER VAR_NAME)
    if(NOT ARG_${_required})
      message(FATAL_ERROR "${_ctx}: ${_required} is required")
    endif()
  endforeach()
  if(NOT ARG_VAR_NAME MATCHES "^[A-Za-z_][A-Za-z0-9_]*$")
    message(FATAL_ERROR "${_ctx}: VAR_NAME \"${ARG_VAR_NAME}\" is not a C++ identifier")
  endif()
  get_filename_component(_file "${ARG_FILE}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
  get_filename_component(_header "${ARG_HEADER}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_BINARY_DIR}")
  if(NOT EXISTS "${_file}")
    message(FATAL_ERROR "${_ctx}: FILE not found: ${_file}")
  endif()

  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_file}")

  # Character literals ('\xe2'), not integers (0xe2): an int above 0x7f is a
  # narrowing conversion to char in a braced initializer, a hard error under
  # -Werror for any file with non-ASCII bytes (UTF-8 dialog titles, say).
  file(READ "${_file}" _hex HEX)
  string(REGEX REPLACE "([0-9a-f][0-9a-f])" "'\\\\x\\1'," _bytes "${_hex}")
  get_filename_component(_file_name "${_file}" NAME)
  file(CONFIGURE OUTPUT "${_header}" CONTENT
"#pragma once
// Generated by pj_embed_file() from ${_file_name} — edit that file, not this header.
inline constexpr char ${ARG_VAR_NAME}[] = {
${_bytes}'\\x00'};
" @ONLY)

  get_filename_component(_header_dir "${_header}" DIRECTORY)
  target_include_directories(${TARGET} PRIVATE "${_header_dir}")
  target_sources(${TARGET} PRIVATE "${_header}")
endfunction()

# ---------------------------------------------------------------------------
# pj_harden_plugin_exports
# ---------------------------------------------------------------------------
# pj_harden_plugin_exports(<target>
#   [FAMILIES <family>...]           # entry points derived as PJ_get_<family>_vtable
#   [REQUIRED_EXPORTS <symbol>...]   # further symbols that must be exported (kept + checked)
#   [EXTRA_EXPORTS <symbol>...])     # symbols to keep exported without checking presence
#
# Linux/ELF only (a silent no-op elsewhere): links the DSO with a version script whose
# `global:` list is the plugin ABI boot symbol (pj_plugin_abi_version), every family entry
# point, and the caller's REQUIRED/EXTRA exports, with `local: *` for everything else. A
# post-build step (PjCheckElfPluginExports.cmake, run in CMake script mode with the
# toolchain's nm) then fails the build if any STB_GNU_UNIQUE symbol is still exported or a
# required entry point is missing.
#
# Why: exported STB_GNU_UNIQUE symbols (vague-linkage statics from headers, statically linked
# gRPC/Abseil/Arrow/protobuf, libstdc++ instantiations) are process-global despite RTLD_LOCAL.
# glibc pins the first DSO providing such a name (dlclose stops unmapping it), a second copy
# of the plugin loaded from another path binds into the first copy's statics with init guards
# already set, and two different plugins embedding the same dependency silently share one
# copy's state. A version script — rather than --exclude-libs,ALL — because
# pj_plugin_abi_version is a weak header-emitted definition that static-archive members on
# the link line also carry: hiding the archive copy would demote every copy through ELF
# visibility merging, whereas the version script selects by final symbol name after
# resolution.
#
# All four family entry points are always kept exported (naming an absent symbol is a
# no-op), so an embedded dialog's PJ_get_dialog_vtable is never localized by mistake;
# FAMILIES decides which of them the gate insists on. PE exports nothing without dllexport
# and Mach-O has no unique binding, so the problem does not exist there.
function(pj_harden_plugin_exports TARGET)
  set(_options)
  set(_oneValueArgs)
  set(_multiValueArgs FAMILIES REQUIRED_EXPORTS EXTRA_EXPORTS)
  cmake_parse_arguments(ARG "${_options}" "${_oneValueArgs}" "${_multiValueArgs}" ${ARGN})
  set(_ctx "pj_harden_plugin_exports(${TARGET})")
  if(ARG_UNPARSED_ARGUMENTS)
    message(FATAL_ERROR "${_ctx}: unknown arguments: ${ARG_UNPARSED_ARGUMENTS}")
  endif()
  _pj_plugin_check_target("${_ctx}" "${TARGET}")
  if(NOT ARG_FAMILIES AND NOT ARG_REQUIRED_EXPORTS)
    message(FATAL_ERROR "${_ctx}: FAMILIES or REQUIRED_EXPORTS is required")
  endif()

  set(_required pj_plugin_abi_version)
  foreach(_family IN LISTS ARG_FAMILIES)
    _pj_plugin_check_family("${_ctx}" "${_family}")
    list(APPEND _required "PJ_get_${_family}_vtable")
  endforeach()
  list(APPEND _required ${ARG_REQUIRED_EXPORTS})
  list(REMOVE_DUPLICATES _required)

  if(NOT CMAKE_SYSTEM_NAME STREQUAL "Linux")
    return()
  endif()

  set(_global
    pj_plugin_abi_version
    PJ_get_data_source_vtable
    PJ_get_message_parser_vtable
    PJ_get_toolbox_vtable
    PJ_get_dialog_vtable
    ${ARG_REQUIRED_EXPORTS}
    ${ARG_EXTRA_EXPORTS})
  list(REMOVE_DUPLICATES _global)
  set(_global_lines "")
  foreach(_symbol IN LISTS _global)
    string(APPEND _global_lines "    ${_symbol};\n")
  endforeach()
  set(_map "${CMAKE_CURRENT_BINARY_DIR}/${TARGET}_exports.map")
  file(CONFIGURE OUTPUT "${_map}" CONTENT
"/* Generated by pj_harden_plugin_exports(${TARGET}) — edit the CMake call, not this file. */
{
  global:
${_global_lines}  local:
    *;
};
" @ONLY)

  set(_checker "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/PjCheckElfPluginExports.cmake")
  target_link_options(${TARGET} PRIVATE "LINKER:--version-script=${_map}")
  # Re-link (and re-gate) when the generated map or the checker changes.
  set_property(TARGET ${TARGET} APPEND PROPERTY LINK_DEPENDS "${_map}" "${_checker}")

  list(JOIN _required "," _required_csv)
  add_custom_command(TARGET ${TARGET} POST_BUILD
    COMMAND ${CMAKE_COMMAND}
      -DPLUGIN_SO=$<TARGET_FILE:${TARGET}>
      -DREQUIRED_EXPORTS=${_required_csv}
      -DNM_TOOL=${CMAKE_NM}
      -P "${_checker}"
    COMMENT "${TARGET}: verifying export allowlist (no STB_GNU_UNIQUE leaks, entry points present)"
    VERBATIM)
endfunction()

# ---------------------------------------------------------------------------
# pj_configure_plugin
# ---------------------------------------------------------------------------
# pj_configure_plugin(<target>
#   FAMILIES <family>...              # data_source | message_parser | toolbox | dialog;
#                                     # the first is the primary family recorded in the sidecar
#   [MANIFEST_FILE <path>]            # default: ${CMAKE_CURRENT_SOURCE_DIR}/manifest.json
#   [MANIFEST_HEADER <path>]          # also embed MANIFEST_FILE as a constexpr header (pj_embed_file)
#   [MANIFEST_VAR <identifier>]       # its variable name; default kPluginManifest
#   [ABI_MAJOR <n>]                   # sidecar hint; default PJ_ABI_VERSION
#   [EXTRA_EXPORTS <symbol>...]       # extra symbols to keep exported (see pj_harden_plugin_exports)
#   [NO_EXPORT_HARDENING])            # skip the export allowlist + gate
#
# The one call that turns `add_library(<target> SHARED ...)` into a correct PlotJuggler
# plugin. Typical use:
#
#   add_library(my_plugin SHARED my_plugin.cpp)
#   target_link_libraries(my_plugin PRIVATE plotjuggler_sdk::plugin_sdk)
#   pj_configure_plugin(my_plugin
#     FAMILIES        data_source dialog
#     MANIFEST_HEADER generated/my_manifest.hpp   # -> #include "my_manifest.hpp"
#     MANIFEST_VAR    kMyManifest)                # -> PJ_DATA_SOURCE_PLUGIN(MyPlugin, kMyManifest)
#
# What it does, in order:
#  1. Validates MANIFEST_FILE: it must exist and hold non-empty string "id", "name", "version".
#  2. Symbol isolation + rpath (see the comment in the body).
#  3. Writes <target>.pjmanifest.json — the source manifest plus "abi_major" and "family" —
#     next to the DSO and installs it alongside. The sidecar is for inspection, packaging
#     diagnostics and developer tooling only: runtime discovery reads the manifest embedded in
#     the DSO, so keep the JSON you pass to PJ_*_PLUGIN() identical to MANIFEST_FILE — easiest
#     with MANIFEST_HEADER, which makes manifest.json the single source.
#  4. MANIFEST_HEADER: pj_embed_file(<target> FILE <manifest> HEADER <h> VAR_NAME <v>).
#  5. Unless NO_EXPORT_HARDENING: pj_harden_plugin_exports(<target> FAMILIES ... EXTRA_EXPORTS ...).
#     Use NO_EXPORT_HARDENING (and call pj_harden_plugin_exports yourself) only when the DSO's
#     entry points are not the standard PJ_get_<family>_vtable set.
function(pj_configure_plugin TARGET)
  set(_options NO_EXPORT_HARDENING)
  set(_oneValueArgs MANIFEST_FILE MANIFEST_HEADER MANIFEST_VAR ABI_MAJOR)
  set(_multiValueArgs FAMILIES EXTRA_EXPORTS)
  cmake_parse_arguments(ARG "${_options}" "${_oneValueArgs}" "${_multiValueArgs}" ${ARGN})
  set(_ctx "pj_configure_plugin(${TARGET})")
  if(ARG_UNPARSED_ARGUMENTS)
    message(FATAL_ERROR "${_ctx}: unknown arguments: ${ARG_UNPARSED_ARGUMENTS}")
  endif()
  _pj_plugin_check_target("${_ctx}" "${TARGET}")
  if(NOT ARG_FAMILIES)
    message(FATAL_ERROR "${_ctx}: FAMILIES is required")
  endif()
  foreach(_family IN LISTS ARG_FAMILIES)
    _pj_plugin_check_family("${_ctx}" "${_family}")
  endforeach()
  list(GET ARG_FAMILIES 0 _primary_family)
  if(ARG_MANIFEST_VAR AND NOT ARG_MANIFEST_HEADER)
    message(FATAL_ERROR "${_ctx}: MANIFEST_VAR requires MANIFEST_HEADER")
  endif()
  if(NOT ARG_MANIFEST_FILE)
    set(ARG_MANIFEST_FILE "${CMAKE_CURRENT_SOURCE_DIR}/manifest.json")
  endif()
  get_filename_component(_manifest "${ARG_MANIFEST_FILE}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
  if(NOT EXISTS "${_manifest}")
    message(FATAL_ERROR "${_ctx}: MANIFEST_FILE not found: ${_manifest}")
  endif()
  if(NOT ARG_ABI_MAJOR)
    # Matches PJ_ABI_VERSION in pj_base/plugin_data_api.h. Bump in lockstep.
    set(ARG_ABI_MAJOR 5)
  endif()

  # --- 1. Manifest validation ------------------------------------------------
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_manifest}")
  file(READ "${_manifest}" _src_json)
  foreach(_key IN ITEMS id name version)
    string(JSON _key_type ERROR_VARIABLE _err TYPE "${_src_json}" "${_key}")
    if(_err OR NOT _key_type STREQUAL "STRING")
      message(FATAL_ERROR "${_ctx}: ${_manifest}: missing required string \"${_key}\" key")
    endif()
    string(JSON _key_value GET "${_src_json}" "${_key}")
    if(_key_value STREQUAL "")
      message(FATAL_ERROR "${_ctx}: ${_manifest}: required string \"${_key}\" key must not be empty")
    endif()
  endforeach()

  # --- 2. Symbol isolation + rpath ------------------------------------------
  # Functional replacement for RTLD_DEEPBIND. Two complementary mechanisms:
  #
  # a. -fvisibility=hidden (compile-time): hides symbols DEFINED in the plugin's
  #    own source files, so the host cannot interpose them.
  # b. -Wl,-Bsymbolic-functions (link-time): makes function calls WITHIN the .so
  #    resolve to the definitions inside it, bypassing the PLT. Critical for
  #    statically bundled deps (e.g. libssl.a from Conan) compiled WITHOUT
  #    -fvisibility=hidden: their symbols enter the .so with DEFAULT visibility,
  #    and without -Bsymbolic-functions their calls would go through the PLT →
  #    the host's namespace first → crash.
  #
  # Together, every function call inside the plugin uses the embedded static
  # copies. The boot-level exports (pj_plugin_abi_version + PJ_get_<family>_vtable)
  # keep visibility("default") via the PJ_*_PLUGIN macros. malloc / pthread /
  # system calls are NOT defined in the plugin, so they still resolve to the
  # host — ASAN malloc interposition works. The version-script allowlist applied
  # in step 5 is the third leg: it also localizes default-visibility symbols
  # that come from static archives. -Bsymbolic-functions is ELF-specific; macOS
  # uses a two-level namespace by default (equivalent behavior).
  set_target_properties(${TARGET} PROPERTIES
    CXX_VISIBILITY_PRESET     hidden
    C_VISIBILITY_PRESET       hidden
    VISIBILITY_INLINES_HIDDEN ON
  )
  if(APPLE)
    set_target_properties(${TARGET} PROPERTIES
      INSTALL_RPATH "@loader_path"
      MACOSX_RPATH  ON
    )
  elseif(UNIX)
    set_target_properties(${TARGET} PROPERTIES
      INSTALL_RPATH "$ORIGIN"
    )
  endif()
  target_link_options(${TARGET} PRIVATE
    $<$<PLATFORM_ID:Linux>:-Wl,-Bsymbolic-functions>
  )

  # --- 3. Sidecar ------------------------------------------------------------
  set(_sidecar_json "${_src_json}")
  string(JSON _sidecar_json SET "${_sidecar_json}" "abi_major" "${ARG_ABI_MAJOR}")
  string(JSON _sidecar_json SET "${_sidecar_json}" "family"    "\"${_primary_family}\"")
  set(_sidecar_path "${CMAKE_CURRENT_BINARY_DIR}/${TARGET}.pjmanifest.json")
  file(CONFIGURE OUTPUT "${_sidecar_path}" CONTENT "${_sidecar_json}\n" @ONLY)
  add_custom_command(
    TARGET ${TARGET} POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E copy_if_different
      "${_sidecar_path}"
      "$<TARGET_FILE_DIR:${TARGET}>/${TARGET}.pjmanifest.json"
    COMMENT "Copying human-readable ${TARGET}.pjmanifest.json next to DSO"
    VERBATIM
  )
  get_target_property(_type ${TARGET} TYPE)
  if(_type STREQUAL "MODULE_LIBRARY" OR _type STREQUAL "SHARED_LIBRARY")
    install(FILES "${_sidecar_path}" DESTINATION "${CMAKE_INSTALL_LIBDIR}")
  endif()

  # --- 4. Manifest header ----------------------------------------------------
  if(ARG_MANIFEST_HEADER)
    if(NOT ARG_MANIFEST_VAR)
      set(ARG_MANIFEST_VAR kPluginManifest)
    endif()
    pj_embed_file(${TARGET}
      FILE     "${_manifest}"
      HEADER   "${ARG_MANIFEST_HEADER}"
      VAR_NAME "${ARG_MANIFEST_VAR}")
  endif()

  # --- 5. Export allowlist + gate -------------------------------------------
  if(NOT ARG_NO_EXPORT_HARDENING)
    pj_harden_plugin_exports(${TARGET}
      FAMILIES      ${ARG_FAMILIES}
      EXTRA_EXPORTS ${ARG_EXTRA_EXPORTS})
  endif()
endfunction()

# ---------------------------------------------------------------------------
# pj_emit_plugin_manifest — deprecated since 0.25.0
# ---------------------------------------------------------------------------
# pj_emit_plugin_manifest(<target> FAMILY <family> [MANIFEST_FILE <path>] [ABI_MAJOR <n>])
#
# The pre-0.25 name. Behaves exactly as it always did — symbol isolation, rpath, manifest
# validation, sidecar; no export allowlist — by forwarding to
# pj_configure_plugin(<target> FAMILIES <family> ... NO_EXPORT_HARDENING). Kept so plugins
# written against older SDKs configure unchanged; new code calls pj_configure_plugin.
function(pj_emit_plugin_manifest TARGET)
  get_property(_warned GLOBAL PROPERTY _PJ_EMIT_PLUGIN_MANIFEST_WARNED)
  if(NOT _warned)
    set_property(GLOBAL PROPERTY _PJ_EMIT_PLUGIN_MANIFEST_WARNED TRUE)
    message(DEPRECATION
      "pj_emit_plugin_manifest() is deprecated since plotjuggler_sdk 0.25.0: call "
      "pj_configure_plugin(<target> FAMILIES <family> ...) instead, which also applies the "
      "export allowlist (see cmake/PjPlugin.cmake).")
  endif()
  set(_options)
  set(_oneValueArgs FAMILY MANIFEST_FILE ABI_MAJOR)
  set(_multiValueArgs)
  cmake_parse_arguments(ARG "${_options}" "${_oneValueArgs}" "${_multiValueArgs}" ${ARGN})
  if(ARG_UNPARSED_ARGUMENTS)
    message(FATAL_ERROR "pj_emit_plugin_manifest(${TARGET}): unknown arguments: ${ARG_UNPARSED_ARGUMENTS}")
  endif()
  if(NOT ARG_FAMILY)
    message(FATAL_ERROR "pj_emit_plugin_manifest(${TARGET}): FAMILY is required")
  endif()
  set(_forward FAMILIES "${ARG_FAMILY}" NO_EXPORT_HARDENING)
  if(ARG_MANIFEST_FILE)
    list(APPEND _forward MANIFEST_FILE "${ARG_MANIFEST_FILE}")
  endif()
  if(ARG_ABI_MAJOR)
    list(APPEND _forward ABI_MAJOR "${ARG_ABI_MAJOR}")
  endif()
  pj_configure_plugin(${TARGET} ${_forward})
endfunction()
